In [1]:
2 ** 1000

10715086071862673209484250490600018105614048117055336074437503883703510511249361224931983788156958581275946729175531468251871452856923140435984577574698574803934567774824230985421074605062371141877954182153046474983581941267398767559165543946077062914571196477686542167660429831652624386837205668069376

In [2]:
import numpy as np

In [3]:
np.int64(2) ** 1000

0

In [4]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [5]:
len(arr)

3

In [6]:
arr[1]

2

In [7]:
type(arr[1])

numpy.int64

In [8]:
arr.dtype

dtype('int64')

In [9]:
arr32 = np.array([1,2,3], dtype=np.int32)
arr32

array([1, 2, 3], dtype=int32)

In [10]:
arr * arr

array([1, 4, 9])

In [21]:
v1 = np.random.rand(1000000)
v2 = np.random.rand(1000000)
print(v1[0], v2[0])

0.7656311663967629 0.40289177890920647


In [22]:
# element by element multiplication
%time v1 * v2

CPU times: user 3.54 ms, sys: 1.72 ms, total: 5.26 ms
Wall time: 3.46 ms


array([0.3084665 , 0.89664145, 0.37419607, ..., 0.00473256, 0.15405268,
       0.13570997])

In [13]:
# total summation of element products (1*1 + 2*2 + 3*3) = 14
np.dot(arr, arr)

14

In [14]:
# @ is reserved for matrix multiplication dot product
arr @ arr

14

In [15]:
mat = np.array([[1,2,3], [4,5,6], [7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
v = np.arange(12)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
v.reshape((4, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
mat = np.arange(12).reshape((4, 3))
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
mat.shape

(4, 3)

In [20]:
mat2 = mat.reshape((3, 4))
mat2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
mat[1,2] = 17

In [25]:
mat

array([[ 0,  1,  2],
       [ 3,  4, 17],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [26]:
mat2

array([[ 0,  1,  2,  3],
       [ 4, 17,  6,  7],
       [ 8,  9, 10, 11]])